version: "3.6"
services:
  postgres:
    image: postgres:14.2
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    env_file:
      - ".env"

volumes:
  postgres_volume: # exec: docker volume create postgres_volume
    external: true # На Windows не создавал volume из-за "invalid permissions"