version: "3.6"
services:
  postgres:
    image: postgres:14.2
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./dev/db.sql:/docker-entrypoint-initdb.d/db.sql"
      - "postgres_volume:/var/lib/postgresql/data"
#    command: "--init-file /data/application/db.sql"
    env_file:
      - ".env"

  redis:
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:6379"

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis

volumes:
  postgres_volume: # exec: docker volume create postgres_volume
    external: true # На Windows не создавал volume из-за "invalid permissions"