version: "3.6"
services:
  postgres:
    image: postgres:14.2
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    env_file:
      - .env

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis

  redis:
    restart: always
    image: redis:6.2-alpine
    ports:
        - "${REDIS_PORT:-6379}:6379"